services:
  - type: web
    name: conversational-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    disk:
      name: chatbot-disk
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
  
  - type: static
    name: chatbot-frontend
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://conversational-chatbot-XXXX.onrender.com