services:
  - type: web
    name: conversational-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    disk:
      name: chatbot-disk
      mountPath: /opt/render/project/src/instance
      sizeGB: 1